services:
- docker
script:
- make
- ls -la | grep pdf
deploy:
  provider: releases
  api_key:
    secure: xxOgvaLr/8kPt8Lygzdkn5abc39Tcgvdo6X+YiJ7rV1uI2vXc1/5KQZc72lBaOALmG3MY2CDJ/GcAQ403OvkWpTLeQmJH4DkAplf5WdhG6veYanuG0x117DoyV/OEE85kuoIhBdeZsmoJIMe2jZVKjyJgnsDarfQ2VpbvJvGl04iAAYHAmtv6JUCqv/N4a1WzyrxpJUIAWKY/LP88XKoTxfUJ60EnVFa8Pyzksv1xP4te35VpbAp6xKj49QZZJXudBBnLNaqwLH0iBdZq1SHZxuXoTQpj14vAXB+tfwYe+1Ge7o6sXLH4Jw4fzcRGmDLg1pO618dH58Vltc3NU22mkvjCGybPtEa4OQVgHM3g12hpXu7zdr+PZNoPeotA84AWtz7oznP1DNmx0J5EmlsZN9HTbXPjLokzwh2/OhTMdfosKkasirRz+svthuFqL7J8NOHPnqtMM/SCWFREUXp00lkTzYkWwmm01E3peUoXD1nZyHj1KOrRArwd0HIFiWQrBVIeejNgfJ8eLcJKeGceQJac5Un3QYB6Nzne/lFRjR8ilq5rPJSG36fLMQevp0F1bgjs9E7+hqdtIO0IibDlKXtW/l1t4swZKFuHEJKR8fCczA7EHYKKQIfDNtv4bVV9B4IhQypUEOGzXQs3b5564EmQSXO3WpI0EsUItysTaE=
  file: project.pdf
  skip_cleanup: true
  on:
    repo: uniba-ktr/ProjTeX
    tags: true
